[package]
name = "overengineer-dis-backend"
version = "0.1.0"
authors = ["j-brn <me@jbrn.eu>"]
edition = "2018"

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.0.0"
dotenv = "0.15.0"
serde = "1.0.104"