apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: overengineer-backend
  labels:
  annotations:
    nginx.org/websocket-services: "overengineer-backend"
spec:
  rules:
  - host: overengineer.wtf
    http:
      paths:
      - path: /backend
        backend:
          serviceName: overengineer-backend
          servicePort: 8080
